//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbuffalortours.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<SlideDetail> SlideDetails { get; set; }
        public virtual DbSet<TextData> TextDatas { get; set; }
        public virtual DbSet<ToursRelated> ToursRelateds { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_SlideDetail> vw_SlideDetail { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
    }
}
