//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbuffalortours.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideDetail
    {
        public int DetailID { get; set; }
        public int SlideID { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public string ImageSmall { get; set; }
        public string ImageLarge { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
