//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbuffalortours.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToursRelated
    {
        public int RelatedID { get; set; }
        public int TourID { get; set; }
        public int TourRelatedID { get; set; }
    }
}
