//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbuffalortours.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int TourID { get; set; }
        public string TourName { get; set; }
        public string ShortDescription { get; set; }
        public string TourContent { get; set; }
        public string HighlightTitle { get; set; }
        public string Highlight { get; set; }
        public int AlbumID { get; set; }
        public string ImageSmall { get; set; }
        public string ImageLarge { get; set; }
        public bool IsHost { get; set; }
        public bool IsActive { get; set; }
    }
}
